### ISSUE TITLE
Two appveyor projects

### ISSUE THREAD

**Issue by isuruf** [conda-forge/numpy_groupies-feedstock#3]
https://ci.appveyor.com/project/conda-forge/numpy-groupies-feedstock-5f9paszbwuo4g2t
https://ci.appveyor.com/project/conda-forge/numpy-groupies-feedstock-dz0j9cgw26yo178

cc @jakirkham

**Comment by jakirkham** [comment]
Right. There’s a way to remove them and it’s a little subtle. We should try to improve `conda-smithy` to handle this case better.

Can you please assign this to me?

**Comment by jakirkham** [comment]
So just now looked at this. Can't seem to access the first link and there is only webhook that is connected to the last project. Guess this is already resolved then. Were you able to make these changes or is there something else that still appears wrong?

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by isuruf** [comment]
No. thanks for looking into it

**Comment by jakirkham** [comment]
Of course. Thanks for checking.
